name: 02-workflow-event

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - name: show the trigger
          run: echo "I have triggered by an ${{github.event_name}} event."