name: 08-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
        - name: Read a variable
          run: echo "My URL value is ${{vars.MY_VAR}}"
          