name: 08-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
        - name: Read a Repository variable
          run: echo "My URL value is ${{vars.MY_VAR}}"

        - name: Print Environment Variable
          run: echo "${{ env.MY_ENVIRONMENT_VARIABLE }}" 

        - name: Print Environment Secret
          run: echo "${{secrets.MY_ENVIRONMENT_SECRET }}" 

        - name: Print Repository Secret
          run: echo "${{secrets.MY_REPOSITORY_SECRET }}" 


