name: 08-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    environment: production
    env:
        Prod_variable: ${{ vars.MY_ENVIRONMENT_VARIABLE }}
    steps:
        - name: Read a Repository variable
          run: echo "My URL value is ${{vars.MY_VAR}}"

        - name: Print Environment Variable
          run: echo "My Environment variable is $Prod_variable" 

        - name: Print Environment Secret
          run: echo "My Environment secret is ${{secrets.TEST_ENVIRINMENT }}" 

        - name: Print Repository Secret
          run: echo "My Repository secret is ${{secrets.MY_REPOSITORY_SECRET }}" 


