name: 08-Youtube-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    environment: Test
    env:
        test_variable: ${{ vars.YOUTUBE_TEST_VARIABLE }}
    steps:
        - name: Print Repository variable
          run: echo "My Repository variable is ${{vars.YOUTUBE_REPOSITORY_VARIABLE}}"

        - name: Print Environment Variable
          run: echo "My test Environment variable is $test_variable" 

        - name: Print Environment Secret
          run: echo "My Dev Environment secret is ${{secrets.YOUTUBE_TEST_SECRET }}" 

        - name: Print Repository Secret
          run: echo "My Repository secret is ${{secrets.YOUTUBE_DEMO_REPOSITORY }}" 


