name: 08-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    environment: Dev
    env:
        dev_variable: ${{ vars.DEV_DEMO_VARIABLE }}
    steps:
        - name: Print Repository variable
          run: echo "My Repository variable is ${{vars.DEMO_REPOSITORY_VARIABLE}}"

        - name: Print Environment Variable
          run: echo "My Dev Environment variable is $dev_variable" 

        - name: Print Environment Secret
          run: echo "My Dev Environment secret is ${{secrets.DEV_DEMO_SECRET }}" 

        - name: Print Repository Secret
          run: echo "My Repository secret is ${{secrets.DEMO_REPOSITORY_SECRET }}" 


