name: 08-secretdemo

on: 
    workflow_dispatch:
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: Read a Repository variable
          run: echo "My URL value is ${{vars.MY_VAR}}"

        - name: Print Environment Variable
          run: echo "My Environment variable is ${{ env.PRODUCTIONVARIABLE }}" 

        - name: Print Environment Secret
          run: echo "My Environment secret is ${{secrets.MY_ENVIRONMENT_SECRET }}" 

        - name: Print Repository Secret
          run: echo "My Repository secret is ${{secrets.MY_REPOSITORY_SECRET }}" 


